// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: api.proto

package service

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GeneratePlaybackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoPath string `protobuf:"bytes,1,opt,name=video_path,json=videoPath,proto3" json:"video_path,omitempty"`
}

func (x *GeneratePlaybackRequest) Reset() {
	*x = GeneratePlaybackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlaybackRequest) ProtoMessage() {}

func (x *GeneratePlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlaybackRequest.ProtoReflect.Descriptor instead.
func (*GeneratePlaybackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePlaybackRequest) GetVideoPath() string {
	if x != nil {
		return x.VideoPath
	}
	return ""
}

type GeneratePlaybackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalVideoPath string `protobuf:"bytes,1,opt,name=original_video_path,json=originalVideoPath,proto3" json:"original_video_path,omitempty"`
	M3U8PlaybackPath  string `protobuf:"bytes,2,opt,name=m3u8_playback_path,json=m3u8PlaybackPath,proto3" json:"m3u8_playback_path,omitempty"`
}

func (x *GeneratePlaybackResponse) Reset() {
	*x = GeneratePlaybackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePlaybackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePlaybackResponse) ProtoMessage() {}

func (x *GeneratePlaybackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePlaybackResponse.ProtoReflect.Descriptor instead.
func (*GeneratePlaybackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePlaybackResponse) GetOriginalVideoPath() string {
	if x != nil {
		return x.OriginalVideoPath
	}
	return ""
}

func (x *GeneratePlaybackResponse) GetM3U8PlaybackPath() string {
	if x != nil {
		return x.M3U8PlaybackPath
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x17, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x50, 0x61, 0x74, 0x68, 0x22, 0x78, 0x0a, 0x18, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x13, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x2c, 0x0a, 0x12, 0x6d, 0x33, 0x75, 0x38, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61,
	0x63, 0x6b, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d,
	0x33, 0x75, 0x38, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x50, 0x61, 0x74, 0x68, 0x32,
	0x56, 0x0a, 0x09, 0x46, 0x66, 0x6d, 0x70, 0x65, 0x67, 0x41, 0x50, 0x49, 0x12, 0x49, 0x0a, 0x10,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b,
	0x12, 0x18, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x62,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x66, 0x66, 0x6d, 0x70, 0x65, 0x67, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_goTypes = []interface{}{
	(*GeneratePlaybackRequest)(nil),  // 0: GeneratePlaybackRequest
	(*GeneratePlaybackResponse)(nil), // 1: GeneratePlaybackResponse
}
var file_api_proto_depIdxs = []int32{
	0, // 0: FfmpegAPI.GeneratePlayback:input_type -> GeneratePlaybackRequest
	1, // 1: FfmpegAPI.GeneratePlayback:output_type -> GeneratePlaybackResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePlaybackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePlaybackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FfmpegAPIClient is the client API for FfmpegAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FfmpegAPIClient interface {
	GeneratePlayback(ctx context.Context, in *GeneratePlaybackRequest, opts ...grpc.CallOption) (*GeneratePlaybackResponse, error)
}

type ffmpegAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewFfmpegAPIClient(cc grpc.ClientConnInterface) FfmpegAPIClient {
	return &ffmpegAPIClient{cc}
}

func (c *ffmpegAPIClient) GeneratePlayback(ctx context.Context, in *GeneratePlaybackRequest, opts ...grpc.CallOption) (*GeneratePlaybackResponse, error) {
	out := new(GeneratePlaybackResponse)
	err := c.cc.Invoke(ctx, "/FfmpegAPI/GeneratePlayback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FfmpegAPIServer is the server API for FfmpegAPI service.
type FfmpegAPIServer interface {
	GeneratePlayback(context.Context, *GeneratePlaybackRequest) (*GeneratePlaybackResponse, error)
}

// UnimplementedFfmpegAPIServer can be embedded to have forward compatible implementations.
type UnimplementedFfmpegAPIServer struct {
}

func (*UnimplementedFfmpegAPIServer) GeneratePlayback(context.Context, *GeneratePlaybackRequest) (*GeneratePlaybackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePlayback not implemented")
}

func RegisterFfmpegAPIServer(s *grpc.Server, srv FfmpegAPIServer) {
	s.RegisterService(&_FfmpegAPI_serviceDesc, srv)
}

func _FfmpegAPI_GeneratePlayback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePlaybackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FfmpegAPIServer).GeneratePlayback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FfmpegAPI/GeneratePlayback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FfmpegAPIServer).GeneratePlayback(ctx, req.(*GeneratePlaybackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FfmpegAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FfmpegAPI",
	HandlerType: (*FfmpegAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePlayback",
			Handler:    _FfmpegAPI_GeneratePlayback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
